 -- 2 a
INSERT INTO StatusItem(StatusName)
VALUES ('Active')
INSERT INTO StatusItem(StatusName)
VALUES ('Inactive')

INSERT INTO Categories(CategoryName)
VALUES ('Drinks')
INSERT INTO Categories(CategoryName)
VALUES ('Cocktails')
INSERT INTO Categories(CategoryName)
VALUES ('Salads')
INSERT INTO Categories(CategoryName)
VALUES ('Soups')
INSERT INTO Categories(CategoryName)
VALUES ('Desserts')
INSERT INTO Categories(CategoryName)
VALUES ('Meals')

INSERT INTO Items(ItemName, Picture, DescriptionItem, Price, CategoryId, StatusId)
VALUES ('Pina Colada','https://bit.ly/2QrZziI',  'Sweet cocktail made with rum, 
cream of coconut or coconut milk, and pineapple juice.', 8.00, 2, 1)
INSERT INTO Items(ItemName, Picture, DescriptionItem, Price, CategoryId, StatusId)
VALUES ('Bay Breeze', NULL,  'Fruit juices and vodka are all you''ll need for this beachy cocktail.', 7.50, 2, 1)
INSERT INTO Items(ItemName, Picture, DescriptionItem, Price, CategoryId, StatusId)
VALUES ('Caesar Salad', NULL, NULL, 6.00, 3, 1)
INSERT INTO Items(ItemName, Picture, DescriptionItem, Price, CategoryId, StatusId)
VALUES ('Coke', NULL, NULL, 1.00, 1, 1)
INSERT INTO Items(ItemName, Picture, DescriptionItem, Price, CategoryId, StatusId)
VALUES ('Vegetable Soup', NULL, NULL, 3.00, 4, 1)
INSERT INTO Items(ItemName, Picture, DescriptionItem, Price, CategoryId, StatusId)
VALUES ('Ice Cream', NULL, NULL, 3.50, 5, 1)
INSERT INTO Items(ItemName, Picture, DescriptionItem, Price, CategoryId, StatusId)
VALUES ('Cake', NULL, NULL, 2.00, 5, 2)
INSERT INTO Items(ItemName, Picture, DescriptionItem, Price, CategoryId, StatusId)
VALUES ('Pasta', NULL, NULL, 2.00, 6, 1)
INSERT INTO Items(ItemName, Picture, DescriptionItem, Price, CategoryId, StatusId)
VALUES ('Chicken', NULL, NULL, 6.25, 6, 1)
INSERT INTO Items(ItemName, Picture, DescriptionItem, Price, CategoryId, StatusId)
VALUES ('Beef', NULL, NULL, 8.25, 6, 2)

INSERT INTO Ingredients(IngredientName)
VALUES ('Pineapple Juice')
INSERT INTO Ingredients(IngredientName)
VALUES ('Cranberry Juice')
INSERT INTO Ingredients(IngredientName)
VALUES ('Vodka')
INSERT INTO Ingredients(IngredientName)
VALUES ('Rum')
INSERT INTO Ingredients(IngredientName)
VALUES ('Vegetables')
INSERT INTO Ingredients(IngredientName)
VALUES ('Water')
INSERT INTO Ingredients(IngredientName)
VALUES ('Pasta')
INSERT INTO Ingredients(IngredientName)
VALUES ('Meat')

INSERT INTO IngredientsItems(ItemId, IngredientId)
VALUES (1, 1)
INSERT INTO IngredientsItems(ItemId, IngredientId)
VALUES (1, 4)
INSERT INTO IngredientsItems(ItemId, IngredientId)
VALUES (2, 1)
INSERT INTO IngredientsItems(ItemId, IngredientId)
VALUES (2, 2)
INSERT INTO IngredientsItems(ItemId, IngredientId)
VALUES (2, 3)
INSERT INTO IngredientsItems(ItemId, IngredientId)
VALUES (3, 5)
INSERT INTO IngredientsItems(ItemId, IngredientId)
VALUES (4, 5)
INSERT INTO IngredientsItems(ItemId, IngredientId)
VALUES (8, 7)
INSERT INTO IngredientsItems(ItemId, IngredientId)
VALUES (8, 8)
INSERT INTO IngredientsItems(ItemId, IngredientId)
VALUES (9, 8)
INSERT INTO IngredientsItems(ItemId, IngredientId)
VALUES (10, 8)

 -- 2 b
-- Receipt/Order 1
INSERT INTO Receipt(TransactionTime, Total)
VALUES (GETDATE(), 0)

INSERT INTO ItemsInReceipt(ReceiptId, ItemId, Quantity)
VALUES (1, 1, 1)
UPDATE Receipt
SET Total = (
SELECT (Items.Price * ItemsInReceipt.Quantity)
FROM Items, ItemsInReceipt
WHERE ItemsInReceipt.ReceiptId = Receipt.Id AND Items.Id = ItemsInReceipt.ItemId AND ItemsInReceipt.Id = 1
)
WHERE Receipt.Id = 1;
